"""Initial migration

Revision ID: 9abd12be5598
Revises: 
Create Date: 2024-12-09 14:21:04.437683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9abd12be5598'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('id_employee',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False,
               existing_server_default=sa.text("'kma'"))
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('face', schema=None) as batch_op:
        batch_op.alter_column('id_employee',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('face_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.alter_column('id_employee',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.alter_column('id_employee',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('face', schema=None) as batch_op:
        batch_op.alter_column('face_data',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('id_employee',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'kma'"))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('id_employee',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
